name: tencentcloud_sms
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  crypto: ^3.0.1
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
