# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root workspace
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  
  # Client API
  - package-ecosystem: 'npm'
    directory: '/client-api'
    schedule:
      interval: 'daily'

  # Database seeder
  - package-ecosystem: 'npm'
    directory: '/prisma/seeder'
    schedule:
      interval: 'daily'

  # Prisma binding NextJS package
  - package-ecosystem: 'npm'
    directory: '/packages/prisma'
    schedule:
      interval: 'daily'
