name: socfony
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  args: ^2.3.0
  get_it: ^7.2.0
  grpc: ^3.0.2
  postgres: ^2.4.1+2
  socfony_protobuf: 
    path: ../shared/protobuf

dev_dependencies:
  lints: ^1.0.0
