name: tencentcloud
description: Tencent Cloud APIs for Dart
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  crypto: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
