name: Test NCC build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v2
        run: npm ci
      - name: Install NCC
        run: npm i -g @vercel/ncc
      - name: Run build
        run: ncc build src/main.ts -o dist
